# Downloads Python image 
FROM python:3.12-alpine

# Create /app
WORKDIR /app

# Add requirement.txt file
ADD requirements.txt .

# Install all package in requirements
RUN pip install -r requirements.txt

# Add Project file
ADD . .

ENTRYPOINT ["python"]

## Start Flask
CMD ["app.py"]
